DROP EXTENSION IF EXISTS pgcrypto;

DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS user_identities CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS DATABASECHANGELOG CASCADE;
DROP TABLE IF EXISTS DATABASECHANGELOGLOCK CASCADE;

DROP TABLE IF EXISTS ATTACHMENTS CASCADE;
DROP TABLE IF EXISTS LECTURES CASCADE;
DROP TABLE IF EXISTS EXAMS CASCADE;
DROP TABLE IF EXISTS ASSIGNMENTS CASCADE;
DROP TABLE IF EXISTS MATERIAL_LINKS CASCADE;
DROP TABLE IF EXISTS MATERIAL_FILES CASCADE;
DROP TABLE IF EXISTS RESOURCES CASCADE;
DROP TABLE IF EXISTS POST_LIKES CASCADE;
DROP TABLE IF EXISTS POSTS CASCADE;
DROP TABLE IF EXISTS FOLDERS CASCADE;
DROP TABLE IF EXISTS COURSE_OFFERING_TEACHERS CASCADE;
DROP TABLE IF EXISTS COURSE_OFFERINGS CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;
DROP TABLE IF EXISTS STUDY_YEARS CASCADE;
DROP TABLE IF EXISTS COMMUNITY_MEMBERS CASCADE;
DROP TABLE IF EXISTS ROLE_PERMISSIONS CASCADE;
DROP TABLE IF EXISTS PERMISSIONS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS COMMUNITIES CASCADE;
DROP TABLE IF EXISTS TEACHER_RATING_VALUES CASCADE;
DROP TABLE IF EXISTS RATING_METRICS CASCADE;
DROP TABLE IF EXISTS TEACHER_RATINGS CASCADE;
DROP TABLE IF EXISTS TEACHERS CASCADE;

DROP TYPE IF EXISTS LECTURE_LOCATION CASCADE;
DROP TYPE IF EXISTS MATERIAL_LINK_TYPE CASCADE;
DROP TYPE IF EXISTS ATTACHMENT_TYPE CASCADE;
DROP TYPE IF EXISTS RESOURCE_TYPE CASCADE;
DROP TYPE IF EXISTS STUDY_YEAR_NAME CASCADE;
DROP TYPE IF EXISTS AUTH_PROVIDER CASCADE;