spring:
  application:
    name: app

  mvc:
    problemdetails:
      enabled: true

  config:
    import: file:.env[.properties]

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/api/v1/auth/oauth2/code/{registrationId}"
          github:
            clientId: ${GITHUB_OAUTH2_CLIENT_ID}
            clientSecret: ${GITHUB_OAUTH2_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/api/v1/auth/oauth2/code/{registrationId}"

logging:
  level:
    org.springframework.security: debug

app:
  mail:
    no-reply-email: no-reply@${EMAIL_DOMAIN}
    support-email: support@${EMAIL_DOMAIN}
    notification-email: notification@${EMAIL_DOMAIN}
    email-verification-token-expiration-sec: ${EMAIL_VERIFICATION_CODE_EXPIRATION_SEC:900}
    password-reset-token-expiration-sec: ${PASSWORD_RESET_TOKEN_EXPIRATION_SEC:900}
  jwt:
    secret: ${SESSION_SECRET}
  session:
    access-token-expiration-sec: ${SESSION_ACCESS_TOKEN_EXPIRATION_SEC}
    refresh-token-expiration-sec: ${SESSION_REFRESH_TOKEN_EXPIRATION_SEC}
    refresh-token-rotate-window-sec: ${SESSION_REFRESH_TOKEN_ROTATE_WINDOW_SEC}
  development:
    client-origin: ${CLIENT_ORIGIN:http://localhost:5173}
    is-development: ${IS_DEVELOPMENT:false}
    origin: ${ORIGIN:http://localhost:8080}
  aws:
     bucket-name: ${AWS_BUCKET_NAME}
     region: ${AWS_REGION}
     access-key: ${AWS_ACCESS_KEY}
     secret-key: ${AWS_SECRET_KEY}
