spring:
  application:
    name: app

  mvc:
    problemdetails:
      enabled: true

  config:
    import: file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/api/v1/login/oauth2/code/{registrationId}"

logging:
  level:
    org.springframework.security: debug


app:
  jwt:
    secret: ${SESSION_SECRET}
  session:
    access-token-expiration-sec: ${SESSION_ACCESS_TOKEN_EXPIRATION_SEC}
    refresh-token-expiration-sec: ${SESSION_REFRESH_TOKEN_EXPIRATION_SEC}

  is-development: ${IS_DEVELOPMENT:false}
