--liquibase formatted sql
--changeset David:005

-- Material Link Type additions
ALTER TYPE MATERIAL_LINK_TYPE ADD VALUE IF NOT EXISTS 'DOCS';
ALTER TYPE MATERIAL_LINK_TYPE ADD VALUE IF NOT EXISTS 'DOCX';

-- Notification Enums
CREATE TYPE NOTIFICATION_CATEGORY AS ENUM ('EVENT', 'POST', 'SYSTEM');
CREATE TYPE EVENT_NOTIFICATION_TYPE AS ENUM ('REMINDER', 'UPDATED', 'CANCELLED');
CREATE TYPE POST_NOTIFICATION_TYPE AS ENUM ('COMMUNITY_POST', 'COURSE_POST', 'COMMENT', 'LIKE');
CREATE TYPE SYSTEM_NOTIFICATION_TYPE AS ENUM ('ANNOUNCEMENT', 'MAINTENANCE', 'GENERAL');

-- Drop old NOTIFICATIONS table and type
DROP TABLE IF EXISTS NOTIFICATIONS CASCADE;
DROP TYPE IF EXISTS NOTIFICATION_TYPE CASCADE;

-- Base NOTIFICATIONS table
CREATE TABLE NOTIFICATIONS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category NOTIFICATION_CATEGORY NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Event notifications sub-table
CREATE TABLE EVENT_NOTIFICATIONS (
    id UUID PRIMARY KEY REFERENCES NOTIFICATIONS(id) ON DELETE CASCADE,
    type EVENT_NOTIFICATION_TYPE NOT NULL,
    event_id UUID REFERENCES EVENTS(id) ON DELETE SET NULL,
    actor_id UUID REFERENCES USERS(id) ON DELETE SET NULL
);

-- Post notifications sub-table
CREATE TABLE POST_NOTIFICATIONS (
    id UUID PRIMARY KEY REFERENCES NOTIFICATIONS(id) ON DELETE CASCADE,
    type POST_NOTIFICATION_TYPE NOT NULL,
    post_id UUID REFERENCES POSTS(id) ON DELETE SET NULL,
    actor_id UUID REFERENCES USERS(id) ON DELETE SET NULL
);

-- System notifications sub-table
CREATE TABLE SYSTEM_NOTIFICATIONS (
    id UUID PRIMARY KEY REFERENCES NOTIFICATIONS(id) ON DELETE CASCADE,
    type SYSTEM_NOTIFICATION_TYPE NOT NULL DEFAULT 'GENERAL'
);

-- Indexes
CREATE INDEX idx_notifications_user_category_created ON NOTIFICATIONS(user_id, category, created_at DESC);
CREATE INDEX idx_notifications_user_unread ON NOTIFICATIONS(user_id, is_read, created_at DESC);
CREATE INDEX idx_event_notifications_event ON EVENT_NOTIFICATIONS(event_id);
CREATE INDEX idx_post_notifications_post ON POST_NOTIFICATIONS(post_id);

-- Enforce single reminder per user per event
ALTER TABLE EVENT_REMINDERS DROP CONSTRAINT IF EXISTS event_reminders_user_id_event_id_offset_minutes_key;
ALTER TABLE EVENT_REMINDERS ADD CONSTRAINT event_reminders_user_id_event_id_key UNIQUE (user_id, event_id);
