import { useState, useMemo } from "react";
import { ArrowRight, ArrowLeft } from "@/components/ui/icons";
import { toast } from "sonner";
import { useUrlFilters } from "@/hooks/useUrlFilters";
import { useUserCommunities } from "@/features/users";
import { useCommunityStudyYears } from "@/features/communities";
import {
  useStudyYearCourses,
  studyYearNameToSlug,
} from "@/features/studyYears";
import { useCalendarStore } from "../store/useCalendarStore";
import { useBatchUpsertEvents } from "../api/events";
import { CALENDAR_FILTER_SCHEMA } from "../schemas/calendarFilterSchema";
import {
  batchEventsArraySchema,
  type BatchEventItemParsed,
} from "../schemas/eventSchemas";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";
import { BatchPromptStep } from "./BatchPromptStep";
import { BatchPasteStep } from "./BatchPasteStep";
import { BatchPreviewStep } from "./BatchPreviewStep";

type Step = 1 | 2 | 3;

export function BatchImportEventsModal() {
  const isOpen = useCalendarStore((s) => s.isBatchModalOpen);
  const onClose = useCalendarStore((s) => s.closeBatchModal);

  const { filters } = useUrlFilters(CALENDAR_FILTER_SCHEMA);
  const communitySlug = filters.community || "";

  // Step state
  const [step, setStep] = useState<Step>(1);
  const [selectedStudyYearState, setSelectedStudyYear] = useState<string>("");
  const [pastedJson, setPastedJson] = useState<string>("");
  const [parsedEvents, setParsedEvents] = useState<BatchEventItemParsed[]>([]);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [currentTime] = useState(() => Date.now());

  // Fetch community details
  const { data: userCommunitiesData } = useUserCommunities(
    {},
    { enabled: isOpen && Boolean(communitySlug) },
  );
  const activeCommunity = useMemo(() => {
    return userCommunitiesData?.content?.find((c) => c.slug === communitySlug);
  }, [userCommunitiesData, communitySlug]);

  // Fetch study years for community
  const { data: studyYears } = useCommunityStudyYears(communitySlug);

  // Derive selected study year from state, filter, or first available
  const selectedStudyYear =
    selectedStudyYearState ||
    filters.studyYear ||
    (studyYears && studyYears.length > 0 ? studyYears[0].studyYearName : "");

  const handleCloseModal = () => {
    setStep(1);
    setSelectedStudyYear("");
    setPastedJson("");
    setParsedEvents([]);
    setValidationError(null);
    onClose();
  };

  // Fetch courses for the selected study year
  const { data: coursesData, isLoading: isLoadingCourses } =
    useStudyYearCourses(
      communitySlug,
      selectedStudyYear ? studyYearNameToSlug(selectedStudyYear) : "",
    );

  const courses = useMemo(() => {
    return (coursesData ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      abbreviation: c.abbreviation,
    }));
  }, [coursesData]);

  // Course map for preview lookups
  const courseMap = useMemo(() => {
    const map = new Map<number, { name: string; abbreviation?: string }>();
    courses.forEach((c) =>
      map.set(c.id, { name: c.name, abbreviation: c.abbreviation }),
    );
    return map;
  }, [courses]);

  // Validate pasted JSON
  const handleValidateJson = () => {
    setValidationError(null);
    const cleaned = pastedJson
      .trim()
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();

    if (!cleaned) {
      setValidationError("Please paste the JSON generated by the LLM.");
      return;
    }

    let rawJson: unknown;
    try {
      rawJson = JSON.parse(cleaned);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Invalid JSON syntax";
      setValidationError(`JSON parsing error: ${msg}`);
      return;
    }

    // Support either direct array or { events: [...] }
    const itemsToValidate = Array.isArray(rawJson)
      ? rawJson
      : typeof rawJson === "object" && rawJson !== null && "events" in rawJson
        ? (rawJson as { events: unknown }).events
        : null;

    if (!Array.isArray(itemsToValidate)) {
      setValidationError(
        "Expected a JSON array of events or an object with an 'events' array.",
      );
      return;
    }

    const parseResult = batchEventsArraySchema.safeParse(itemsToValidate);
    if (!parseResult.success) {
      const firstIssue = parseResult.error.issues[0];
      const path = firstIssue.path.join(".");
      setValidationError(
        `Validation error at ${path || "root"}: ${firstIssue.message}`,
      );
      return;
    }

    setParsedEvents(parseResult.data);
    setStep(3);
  };

  // Batch mutation
  const { mutateAsync: batchUpsert, isPending: isSubmitting } =
    useBatchUpsertEvents();

  // Check if any event is in the past
  const pastEventsCount = useMemo(() => {
    return parsedEvents.filter(
      (ev) => new Date(ev.startTime).getTime() < currentTime,
    ).length;
  }, [parsedEvents, currentTime]);

  // Sync edits from preview step to state & JSON
  const handleUpdateEvents = (updatedList: BatchEventItemParsed[]) => {
    setParsedEvents(updatedList);
    setPastedJson(JSON.stringify(updatedList, null, 2));
  };

  // Submit batch import
  const handleConfirmImport = async () => {
    if (!communitySlug) {
      toast.error("No community selected");
      return;
    }

    if (pastEventsCount > 0) {
      toast.error("Cannot import events scheduled in the past");
      return;
    }

    try {
      const res = await batchUpsert({
        communitySlug,
        events: parsedEvents.map((e) => ({
          courseId: e.courseId,
          title: e.title,
          description: e.description ?? undefined,
          type: e.type,
          startTime: e.startTime,
          durationHours: e.durationHours ?? undefined,
          location: e.location,
          locationDetails: e.locationDetails ?? undefined,
        })),
      });

      toast.success(
        `Batch processed: ${res.createdCount} created, ${res.updatedCount} updated`,
      );
      handleCloseModal();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Batch import failed";
      toast.error(msg);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && handleCloseModal()}>
      <DialogContent
        className="max-w-3xl max-h-[90vh] flex flex-col p-0 gap-0 overflow-hidden"
        aria-describedby="batch-import-description"
      >
        {/* Header */}
        <DialogHeader className="shrink-0">
          <div className="flex items-center gap-2">
            <div>
              <DialogTitle className="text-xl font-bold font-heading">
                Batch Import Events
              </DialogTitle>
              <DialogDescription
                id="batch-import-description"
                className="text-xs text-muted-foreground mt-0.5"
              >
                Import lecture schedules or exam dates extracted from documents
                via an LLM.
              </DialogDescription>
            </div>
          </div>

          {/* Responsive Stepper Tabs */}
          <div className="flex items-center justify-between gap-1 sm:gap-2 mt-4 text-xs font-semibold w-full">
            <div
              className={cn(
                "flex items-center gap-1.5 px-2.5 sm:px-3 py-1 rounded-full border transition-colors shrink-0",
                step === 1
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-muted text-muted-foreground border-transparent",
              )}
            >
              <span>1</span>
              <span
                className={cn(
                  "text-[11px] sm:text-xs",
                  step === 1 ? "inline" : "hidden sm:inline",
                )}
              >
                Generate Prompt
              </span>
            </div>
            <div className="flex-1 h-px bg-border min-w-2" />
            <div
              className={cn(
                "flex items-center gap-1.5 px-2.5 sm:px-3 py-1 rounded-full border transition-colors shrink-0",
                step === 2
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-muted text-muted-foreground border-transparent",
              )}
            >
              <span>2</span>
              <span
                className={cn(
                  "text-[11px] sm:text-xs",
                  step === 2 ? "inline" : "hidden sm:inline",
                )}
              >
                Paste JSON
              </span>
            </div>
            <div className="flex-1 h-px bg-border min-w-2" />
            <div
              className={cn(
                "flex items-center gap-1.5 px-2.5 sm:px-3 py-1 rounded-full border transition-colors shrink-0",
                step === 3
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-muted text-muted-foreground border-transparent",
              )}
            >
              <span>3</span>
              <span
                className={cn(
                  "text-[11px] sm:text-xs",
                  step === 3 ? "inline" : "hidden sm:inline",
                )}
              >
                Preview & Confirm
              </span>
            </div>
          </div>
        </DialogHeader>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {step === 1 && (
            <BatchPromptStep
              selectedStudyYear={selectedStudyYear}
              onSelectStudyYear={(val) => setSelectedStudyYear(val)}
              studyYears={studyYears}
              communityName={activeCommunity?.name || communitySlug}
              courses={courses}
              isLoadingCourses={isLoadingCourses}
            />
          )}

          {step === 2 && (
            <BatchPasteStep
              value={pastedJson}
              onChange={(val) => setPastedJson(val)}
              validationError={validationError}
              onClearError={() => setValidationError(null)}
            />
          )}

          {step === 3 && (
            <BatchPreviewStep
              parsedEvents={parsedEvents}
              courseMap={courseMap}
              communityName={activeCommunity?.name || communitySlug}
              communitySlug={communitySlug}
              pastEventsCount={pastEventsCount}
              currentTime={currentTime}
              onUpdateEvents={handleUpdateEvents}
            />
          )}
        </div>

        {/* Footer */}
        <DialogFooter className="px-6 py-4 border-t border-border/40 shrink-0 flex items-center justify-between">
          {step === 1 && (
            <>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleCloseModal}
                className="w-full sm:w-auto"
              >
                Cancel
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={() => setStep(2)}
                className="gap-1.5 w-full sm:w-auto"
              >
                <span>Continue to Paste JSON</span>
                <ArrowRight className="size-3.5" />
              </Button>
            </>
          )}

          {step === 2 && (
            <>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setStep(1)}
                className="w-full sm:w-auto gap-1.5"
              >
                <ArrowLeft className="size-3.5" />
                <span>Back</span>
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleValidateJson}
                className="w-full sm:w-auto gap-1.5"
              >
                <span>Validate & Preview</span>
                <ArrowRight className="size-3.5" />
              </Button>
            </>
          )}

          {step === 3 && (
            <>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setStep(2)}
                disabled={isSubmitting}
                className="w-full sm:w-auto gap-1.5"
              >
                <ArrowLeft className="size-3.5" />
                <span>Back to JSON</span>
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleConfirmImport}
                disabled={
                  isSubmitting ||
                  pastEventsCount > 0 ||
                  parsedEvents.length === 0
                }
                className="w-full sm:w-auto gap-1.5"
              >
                {isSubmitting ? (
                  <>
                    <Spinner className="size-3.5" />
                    <span>Importing...</span>
                  </>
                ) : (
                  <>
                    <span>Import {parsedEvents.length} Events</span>
                  </>
                )}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
